### ISSUE TITLE
Release Issue and status tracking for an initial release

### ISSUE THREAD

**Issue by VijayanB** [opensearch-project/opensearch-net#14]
Release .NET client for OpenSearch

- [ ]  Workflow should be green
- [x] remove amazon from copyright message
- [ ]  Add an example to readme
- [x] Do we have integration tests?

**Comment by anirudha** [comment]
.NET Client
 
Source code renamed - Feb 4th Done
Unit tests enabled - Feb 11th Done
Integration tests enabled - Mar 22nd - On Track

Abstractions project renamed -  In Progress
Full integration tests - In Progress

Full release of .NET client - Apr 4th -  Not Started

Integration tests passing with security enabled  -  Not Started

Release task checklist  -  Not Started

> Regression tests
> Status badges
> Switch to new signing keys
> Fork main branch for future releases
> Automate publishing nuget packages

**Comment by alexmeizer** [comment]
Here's an issue tracking the integration tests:
https://github.com/opensearch-project/opensearch-net/issues/27

**Comment by anirudha** [comment]
NuGET accounts are created, tracking release as the next action item

**Comment by CindyKee** [comment]
When are we going to see the .NET clients released to NuGet? It's been 22 days since the last update.

**Comment by Yury-Fridlyand** [comment]
.Net client was [released](https://github.com/opensearch-project/opensearch-net/releases/tag/v1.0.0) today and published on [Nuget](https://www.nuget.org/profiles/opensearchproject).
