### ISSUE TITLE
Milestone 1 tasks

### ISSUE THREAD

**Issue by guiangumpac** [opensearch-project/opensearch-net#16]
- [x]  Delete all older branches < 7.10
- [x]  Delete all released tags
- [x]  Delete main branch(this branch potentially tracks of all 8.x features as well)
- [x]  create main branch from 7.x branch
- [x]  Remove product checker commit if present (this is required to make clients work with oss cluster)
- [x]  Copy template files related to OpenSearch guidelines.
- [x]  Delete docs, examples folder
- [x]  set up CI and ensure tests pass for Elasticsearch OSS Docker image. This means all the test cases related to oss features from 7.10.2 executes successfully.
