### ISSUE TITLE
Milestone 2 tasks

### ISSUE THREAD

**Issue by guiangumpac** [opensearch-project/opensearch-net#17]
In this milestone, we focus on cleaning up existing code and make it ready for OpenSearch development

- [x]  Remove X-Pack and non oss features/tests and commits not related to >7.10 from main branch
- [x]  Update CI to run with Opendistro docker image with out security plugin (all tests should pass)
- [x]  Update Admin.md/MAINTAINERS.md to reflect Individual owners
- [x]  Onboard external maintainers

**Comment by guiangumpac** [comment]
CI runs with Opendistro tarball instead of docker
