### ISSUE TITLE
Milestone 3 tasks

### ISSUE THREAD

**Issue by guiangumpac** [opensearch-project/opensearch-net#18]
In this milestone, we focus on refactoring changes and make it work with OpenSearch 1.0.0 clusters

- [x]  Namespace changes and other refactoring on main branch to support OpenSearch
- [x]  Repo should be made public
- [x]  CI is expected to pass for OpenSearch and OpenDistro with and with out security
