### ISSUE TITLE
Milestone 4 tasks

### ISSUE THREAD

**Issue by guiangumpac** [opensearch-project/opensearch-net#19]
In this milestone, we focus on getting ready for the release and setting up branches for future development

- [x]  Add header flags that need to be supported for compatibility
- [x]  fork main branch to 1.0 branch for release, 1.x branch for future releases
- [x]  delete all other unwanted branches
- [x]  Accept either ELASTICSEARCH_URL or OPENSEARCH_URL
- [x]  Add status badge
- [x]  Add simple connection code to README to get started and get reviewed from Andrew
- [ ]  Able to generate desired artifacts

**Comment by dblock** [comment]
I think we can close this.
