### ISSUE TITLE
1.1 .Net client release with OpenSearch 2.0 support

### ISSUE THREAD

**Issue by Yury-Fridlyand** [opensearch-project/opensearch-net#76]
Acceptance criteria
---------------------
- [x] All CI pass
- [x] OpenSearch 2.0 is fully supported
- [x] OpenSearch 1.x is fully supported
- [x] No breaking changes
- [x] Nuget packages are available for download and use

PR to complete
-----------------
- [x] https://github.com/opensearch-project/opensearch-net/pull/93
- [x] https://github.com/opensearch-project/opensearch-net/pull/92
- [x] https://github.com/opensearch-project/opensearch-net/pull/51
- [x] https://github.com/opensearch-project/opensearch-net/issues/80 - done in scope of #51
- [x] https://github.com/opensearch-project/opensearch-net/pull/88

Release Process
-----------------
https://github.com/opensearch-project/opensearch-net/blob/main/RELEASING.md

- [x] Release branch created for `1.1` release
- [x] Release branch created for the next `1.x` release

See also
---------
- [x] https://github.com/opensearch-project/opensearch-net/issues/34
- [x] https://github.com/opensearch-project/opensearch-net/issues/74
- [ ] https://github.com/opensearch-project/opensearch-net/issues/79

**Comment by thespatt** [comment]
Being that 1.0.0 of the .net client does not work with OpenSearch:
![image](https://user-images.githubusercontent.com/7925173/184930555-efa55bb9-74da-4efc-b046-ae328c7682a4.png)
Is there a reason `2.0` isn't more appropriate than `1.1`? I think it would eliminate some confusion.

**Comment by Yury-Fridlyand** [comment]
It is supposed that next release of the client would have version 1.1. Anyway it will support OpenSearch 2.0. Please, see compatibility matrix in PR #51.
The client version is TBD actually, it could be released as 2.0.

**Comment by wbeckler** [comment]
@thespatt The logic is that, under semver principles, saying "2.0" means that this client breaks compatibility with 1.0. Instead, it only adds features, so it should be incrememted.

The day might come when a version of the client actually does become incompatible with current working application code. In that case we'd increment the major version as a signal that application builders need to do a heavier duty upgrade rather than just a version increment.

**Comment by harshavamsi** [comment]
@Yury-Fridlyand @MaxKsyunz can you create a `1.1` branch with all commits for release?

**Comment by Yury-Fridlyand** [comment]
@harshavamsi,
Done: [1.1.0](https://github.com/opensearch-project/opensearch-net/tree/1.1.0)

**Comment by Yury-Fridlyand** [comment]
https://github.com/opensearch-project/opensearch-net/releases/tag/v1.1.0
